### ISSUE TITLE
Why does createClient print to System.out?

### ISSUE THREAD

**Issue by ddebrunner** [ibm-watson-iot/iot-java#10]
Why does createClient print all the authentication information to System.out?

https://github.com/ibm-messaging/iot-java/blob/387925447bd49fe3ad64d9e9db613b0c39907504/src/com/ibm/iotf/client/AbstractClient.java#L151

**Comment by sathipal** [comment]
Thank you for reporting the issue !!

Removed the System.out and published a new release - 0.0.7.
