### ISSUE TITLE
Can we  make the library support Android out of the box?

### ISSUE THREAD

**Issue by daw3rd** [ibm-watson-iot/iot-java#106]
Issue #11 which is closed, provides a fix to apparently enable this library on Android.  However, this seems to be a bit of a hassle.  Or, might we get a real sample that works on Android?

**Comment by ValkA** [comment]
have you managed to use ApiClient class ?
see #113.

**Comment by amitmangalvedkar** [comment]
We have passed this request of providing an Android library to the architecture team and will get back to you, once we have the final response.

**Comment by amitmangalvedkar** [comment]
We have been receiving multiple requests for this. One more request is [113](https://github.com/ibm-watson-iot/iot-java/issues/113)

**Comment by daw3rd** [comment]
We are using this on Android with mixed success.  The events show up on IoT platform as new "state", but don't seem to show up as new "events".  We can plot the data coming it though.  Odd.  This may be related to the use of Apache httpclient, which is not well supported on Android - see http://hc.apache.org/httpcomponents-client-4.3.x/android-port.html

**Comment by durera** [comment]
I'm working on a major update to the code .. I haven't done any Android development before I'm afraid, if you can point me at any documentation regarding how to test that this works on Android, or even what limitations need to be met to run on Android I will see what I can do as part of that work

**Comment by durera** [comment]
Closing as stale
