### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by ddebrunner** [ibm-watson-iot/iot-java#11]
The client doesn't seem to connect on Android, just keeps repeating making connection attempt with no obvious errors or stacktraces.

I see there is an iot-starter-for-android project, but wondering what the longer term plan is, a single client or two separate clients with different apis?

**Comment by robert17** [comment]
The iot-starter-for-android project is a sample application that makes use of the Eclipse Paho MQTT Android service which uses the Eclipse Paho Java client.
That project was created before these iot-\* libraries were created and isn't currently using them.

**Comment by ddebrunner** [comment]
Any idea if this client (iot-java) is meant to support Android?

**Comment by ddebrunner** [comment]
Thanks to @robert17 I got the client working on Android by updating/patching the Security Provider as described here:

http://developer.android.com/training/articles/security-gms-provider.html

Thanks Again!
