### ISSUE TITLE
Can't find jar org.eclipse.paho.client.mqttv3

### ISSUE THREAD

**Issue by Zerppen** [ibm-watson-iot/iot-java#116]
when i cloned this project then excuted `mvn clean package` got this ERROR:
[ERROR] Failed to execute goal on project watson-iot: Could not resolve dependencies for project com.ibm.messaging:watson-iot:jar:0.2.6: Failure to find org.eclipse.paho:org.eclipse.paho.client.mqttv3:jar:1.1.2-SNAPSHOT in http://maven.aliyun.com/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of nexus-aliyun has elapsed

I tried to find this jar on www.findjar.com but failed ：
No result found 

So,i need help or advice

**Comment by Zerppen** [comment]
yes i can download it and add local dependencie,but i don't think is good.

**Comment by Zerppen** [comment]
i resolved this problem.
And i want to push my fixed code

**Comment by Zerppen** [comment]
@isramos

**Comment by amitmangalvedkar** [comment]
@Zerppen , Could you please provide the exact release and the maven version that you have used? I am asking this because I am unable to recreate this defect using release v0.2.6 and maven 3.5.2.

**Comment by Zerppen** [comment]
changed the maven dependency for mqttv3.jar.Then it works.
        **
`<dependency>
            <groupId>org.eclipse.paho</groupId>
            <artifactId>org.eclipse.paho.client.mqttv3</artifactId>
            <version>1.1.0</version>
        </dependency>`
**
I don't think it's my maven version due to this problem.I am using release 0.2.6 and apache maven 3.3.9

**Comment by amitmangalvedkar** [comment]
@Zerppen Please raise a pull request containing the pom file, on verification, we would accept the request.

**Comment by Zerppen** [comment]
@amitmangalvedkar 
It is my pom file:

**<project
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.ibm.messaging</groupId>
    <artifactId>watson-iot</artifactId>
    <version>0.2.6</version>
    <packaging>jar</packaging>
    <name>ibm-messaging/iot-java</name>
    <description>IBM Watson IoT client library to simplify device/gateway/application interactions with the IoT Platform</description>
    <url>https://github.com/ibm-messaging/iot-java</url>

    <scm>
        <url>https://github.com/ibm-messaging/iot-java</url>
        <connection>scm:git:git@github.com:ibm-messaging/iot-java.git</connection>
        <developerConnection>scm:git:git@github.com:ibm-messaging/iot-java.git</developerConnection>
    </scm>

    <issueManagement>
        <url>https://github.com/ibm-messaging/iot-java/issues</url>
        <system>Issues @ GitHub</system>
    </issueManagement>

    <licenses>
        <license>
            <name>Eclipse Public License - v 1.0</name>
            <url>https://github.com/ibm-messaging/iot-java/blob/master/LICENSE</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <name>Amit M Mangalvedkar</name>
            <email>amitmangalvedkar@in.ibm.com</email>
            <organization>IBM</organization>
            <organizationUrl>http://www.ibm.com</organizationUrl>
        </developer>
         <developer>
            <name>Sathiskumar Palaniappan</name>
            <email>sathipal@in.ibm.com</email>
            <organization>IBM</organization>
            <organizationUrl>http://www.ibm.com</organizationUrl>
        </developer>
    </developers>
    
    <distributionManagement>
  		<snapshotRepository>
	    	<id>ossrh</id>
	    	<url>https://oss.sonatype.org/content/repositories/snapshots</url>
	  	</snapshotRepository>
  		<repository>
    		<id>ossrh</id>
    		<url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
  		</repository>
	</distributionManagement>
	<repositories>
	    <repository>
		<id>Eclipse Paho Repo</id>
		<url>https://repo.eclipse.org/content/repositories/paho-snapshots/</url>
	    </repository>
	</repositories>

    <properties>
        
        <java.version>1.7</java.version>

        
        <maven.compiler.source>1.7</maven.compiler.source>
        <maven.compiler.target>1.7</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.6.1</version>
        </dependency>
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>1.2.17</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.hamcrest</groupId>
            <artifactId>hamcrest-core</artifactId>
            <version>1.3</version>
            <scope>test</scope>
        </dependency>
       <dependency>
            <groupId>org.eclipse.paho</groupId>
            <artifactId>org.eclipse.paho.client.mqttv3</artifactId>
            <version>1.1.0</version>
        </dependency>
        <dependency>
            <groupId>commons-net</groupId>
            <artifactId>commons-net</artifactId>
            <version>3.3</version>
        </dependency>
        <dependency>
            <groupId>commons-logging</groupId>
            <artifactId>commons-logging</artifactId>
            <version>1.2</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.4</version>
        </dependency>
        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
            <version>1.10</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.1</version>
        </dependency>
        <dependency>
            <groupId>joda-time</groupId>
            <artifactId>joda-time</artifactId>
            <version>2.9.2</version>
        </dependency>

        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk16</artifactId>
            <version>1.45</version>
        </dependency>

		<dependency>
    	    <groupId>org.apache.httpcomponents</groupId>
    	    <artifactId>httpmime</artifactId>
    	    <version>4.3.1</version>
		</dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.5.1</version>
                <configuration>
                    <source>${maven.compiler.source}</source>
                    <target>${maven.compiler.target}</target>
                    <compilerArgs>
                    	<args>-Xlint:unchecked</args>
                    	<args>-Xlint:deprecation</args>                    	
                    </compilerArgs>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>2.7</version>
                <configuration>
                    <delimiters>
                        <delimiter>@</delimiter>
                    </delimiters>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.6</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                            <addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>2.10.3</version>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>2.4</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-gpg-plugin</artifactId>
                <version>1.5</version>
                <executions>
                    <execution>
                        <id>sign-artifacts</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>sign</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.sonatype.plugins</groupId>
                <artifactId>nexus-staging-maven-plugin</artifactId>
                <version>1.6.3</version>
                <extensions>true</extensions>
                <configuration>
                    <serverId>ossrh</serverId>
                    <nexusUrl>https://oss.sonatype.org/</nexusUrl>
                    <autoReleaseAfterClose>false</autoReleaseAfterClose>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-release-plugin</artifactId>
                <version>2.5</version>
                <configuration>
                    <autoVersionSubmodules>true</autoVersionSubmodules>
                    <useReleaseProfile>false</useReleaseProfile>
                    <releaseProfiles>release</releaseProfiles>
                    <goals>deploy</goals>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-shade-plugin</artifactId>
                <version>2.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <shadedArtifactAttached>true</shadedArtifactAttached>
                            <shadedClassifierName>with-deps</shadedClassifierName>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>

**
And it 's good.But if insted of  the dependency `org.eclipse.paho:org.eclipse.paho.client.mqttv3:jar:1.1.2-SNAPSHOT`
it can't get the jar any more.

**Comment by amitmangalvedkar** [comment]
I have added Paho 1.2.0 in the maven dependencies, in place of 1.1.2-SNAPSHOT. Once the pull request gets merged, we can close this issue.

**Comment by koyaniv** [comment]
Hi,

Im sorry, but im trying to add the dependency to POM.xml and still get the error message:

**The dependency:**
`        <dependency>
            <groupId>org.eclipse.paho</groupId>
            <artifactId>org.eclipse.paho.client.mqttv3</artifactId>
            <version>1.2.5</version>
        </dependency>`

**The Error:**
Dependency 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5' **not found**

What should I do ?
