### ISSUE TITLE
When did TLS 1.2 support start?

### ISSUE THREAD

**Issue by daw3rd** [ibm-watson-iot/iot-java#125]
Does the recent announcement from IoT regarding TLS 1.2 effect what level of code we should be using.

See https://console.bluemix.net/docs/get-support/appsectls.html#tlssupportwithdraw

**Comment by amitmangalvedkar** [comment]
@daw3rd : You can use the latest release 0.2.6, we are working on release 1.0 which would be made available soon.

**Comment by daw3rd** [comment]
I'm currently using 0.2.2.   If an upgrade from 0.2.2 is required, what  is the minimum level required to get TLS 1.2 support.  I'd rather not have to 0.2.6 right now since I get StackOverFlow in tomcat on a bouncycastle jar when I do that (https://stackoverflow.com/questions/29955410/how-do-i-fix-stackoverflowerror-in-org-apache-catalina-startup-contextconfig-pop/29955411).

**Comment by amitmangalvedkar** [comment]
The support for TLS 1.1 has been revoked and we always encourage developers to switch to the latest release level. So I would suggest please upgrade to v0.2.6

**Comment by amitmangalvedkar** [comment]
If there are no futher queries on this one, I would like to close it.

**Comment by icraggs** [comment]
I'm going to close this issue.  If there are further questions, it can be reopened.  Thanks.
