### ISSUE TITLE
bug in registerDeviceUnderGateway()

### ISSUE THREAD

**Issue by cmigibm** [ibm-watson-iot/iot-java#128]
I think there is a bug with method registerDeviceUnderGateway() in https://github.com/ibm-watson-iot/iot-java/blob/master/src/main/java/com/ibm/iotf/client/api/APIClient.java 

Looks to me that what it only does it to create a deviceId under a device type. Well, the device does not have the same functionality as device that is automatically registered when a gateway publish on its behalf.

So for instance, this won't have any effect gwClient.publishDeviceEvent(DEVICE_TYPE, SIMULATOR_DEVICE_ID, "blink", event); when we use a device created with registerDeviceUnderGateway(). 

but, if you would publish event with  gwClient.publishDeviceEvent(DEVICE_TYPE, SIMULATOR_DEVICE_ID, "blink", event);  where DEVICE_TYPE, SIMULATOR_DEVICE_ID are not from the ones created with registerDeviceUnderGateway().  but any other values, then this would work just fine.

*workaround*

the work around, would be for the customer to not use registerDeviceUnderGateway() and directly start to use gwClient.publishDeviceEvent(DEVICE_TYPE, SIMULATOR_DEVICE_ID, "blink", event); and replace DEVICE_TYPE, SIMULATOR_DEVICE_ID in method, with the values they desire for the gateway to autoregister.

So:

So we can create a device with a specific functions before publishing on it. 
This  function is registerDeviceUnderGateway()
In this moment publishing on a device created previously with registerDeviceUnderGateway is not working.
So we need to publish on it without creating it with registerDeviceUnderGateway, but using " gwClient.publishDeviceEvent " directly.
The process of publish will create the device if not exists otherwise it will publish only on it.

**Comment by miketran78727** [comment]
I agree now that newly created device should be added to the resource groups (if any) of the gateway.  

By the way, this `registerDeviceUnderGateway()` method was implemented before device auto-registration was implemented in the platform.

**Comment by miketran78727** [comment]
This is now fixed in master branch.
