### ISSUE TITLE
Add maven support to project

### ISSUE THREAD

**Issue by durera** [ibm-watson-iot/iot-java#13]
Update this project so that it can be built using maven (create a pom.xml) rather than the (temporary, but we're still using it a year later) build.xml that I knocked up at the start :)

The end goal should be that we can run "maven deploy" to build, test and publish the library to central repo, so that anyone can automatically import this dependency into their projects just by adding it as a dependency in their pom.

**Comment by sathipal** [comment]
The artifact is already available in maven repository, hence closing the issue.
