### ISSUE TITLE
Bulk device operations throw an error even if all individual devices are processed successfully

### ISSUE THREAD

**Issue by saulimus** [ibm-watson-iot/iot-java#130]
Device bulk operations, such as apiClient.deleteMultipleDevices() will throw an "com.ibm.iotf.client.IoTFCReSTException: Some devices deleted successfully" exception when the status code is 202 even if all of the devices were processed succesfully.
See: https://docs.internetofthings.ibmcloud.com/apis/swagger/v0002/org-admin.html#!/Device_Bulk_Configuration
Example of a 202 response that causes the exception to be thrown:
`
[
  {
    "typeId": "string",
    "deviceId": "string",
    "success": true
  }
]
`

To work around this, I've had to catch the exception, check for status code of 202, parse the result and check each "success" property.
I think the client API should take care of this instead of leaving it to the user.

**Comment by miketran78727** [comment]
This is a bug in the platform API.  I have opened an internal issue for our team to investigate.

**Comment by miketran78727** [comment]
The fix is now in master branch. It will be available in next release.
