### ISSUE TITLE
The 404 exception message for getDevice API is misleading

### ISSUE THREAD

**Issue by yangzhang-ibm** [ibm-watson-iot/iot-java#132]
When 404 is returned by the getDevice API, the exception message printed by the java client is always `HttpCode :404 ErrorMessage :: The device type does not exist` even though I am sure the device type does exist and it is the `deviceId` which I provided in the request actually doesn't exist.

For someone who is new to the iot java client, this misleading exception message may cause confusion and even possibly a support ticket from customer to our IoT Platform complaining that the REST API isn't working properly. So it's worthwhile to refine this exception message.

**Comment by yangzhang-ibm** [comment]
I will create a PR with the code change for this issue.

**Comment by yangzhang-ibm** [comment]
The PR is ready: https://github.com/ibm-watson-iot/iot-java/pull/133, could anyone please help review and merge it? Thanks!

**Comment by durera** [comment]
PR merged
