### ISSUE TITLE
The MQTT and HTTP libraries should be completely distinct from each other.

### ISSUE THREAD

**Issue by miketran78727** [ibm-watson-iot/iot-java#139]
We should separate MQTT and HTTP parts of the Java client library. 

For HTTP, using swagger-codegen (https://swagger.io/tools/swagger-codegen/) to for code genration.

**Comment by icraggs** [comment]
Hi Mike.  The *only* important issue right now is MQTT v5 support.  I'm going to close this issue until 2019 when might be reopened and looked at then.
