### ISSUE TITLE
javax.servlet and com.ibm.json4j dependencies?

### ISSUE THREAD

**Issue by dlaboss** [ibm-watson-iot/iot-java#14]
Neither are listed as dependencies but their jars are included in lib and referenced in .classpath.  Can they be removed?

**Comment by sathipal** [comment]
These jars are required for building the sample application included within the library, but not required to build the library itself. 

We are planning to add a maven support in the coming week, so this will be taken care as part of that. Thank you for contacting us.

**Comment by sathipal** [comment]
The related jars are removed from the lib folder, hence closing the issue.
