### ISSUE TITLE
Add support for MQTT Version 5 

### ISSUE THREAD

**Issue by miketran78727** [ibm-watson-iot/iot-java#140]
Add MQTT Version 5 support using Paho Java client

MQTT version 5 features to be documented.

**Comment by icraggs** [comment]
There are many improvements to MQTT version 5 over MQTT version 3, we need to find out which to prioritise.

**Comment by rdasgupt** [comment]
Paho JAVA MQTTv5 client library is officially not released yet. It is expected to be released by 15th May 2020. Work on this issue will continue once v5 is available.

**Comment by durera** [comment]
Closing issue, IBM Watson IoT Platform has been withdrawn from market as of December 9, 2020. See: https://www-01.ibm.com/common/ssi/cgi-bin/ssialias?subtype=ca&infotype=an&appname=iSource&supplier=897&letternum=ENUS920-136#rprodnx for more information
