### ISSUE TITLE
IBM Watson IoT Platform API samples repo

### ISSUE THREAD

**Issue by SKMoon1** [ibm-watson-iot/iot-java#144]
Noticed the repository has been moved but the links have not been updated.

![image](https://user-images.githubusercontent.com/41284920/48834143-b18c5f00-ed85-11e8-93f1-a9d296d402f7.png)

**Comment by miketran78727** [comment]
I will fix these links.. Thanks for letting us know.

**Comment by miketran78727** [comment]
Fixed and merged.
