### ISSUE TITLE
IBM IOT support rule engines?

### ISSUE THREAD

**Issue by wuwei3** [ibm-watson-iot/iot-java#156]
Does IBM IOT support rule engines action?

I saw it is upgrading while I entering the "Rule" tab, when it is available? 

I can create the interface by API for now, if I want to use the rule engines right now, it is useful?

If YES, how to make the rule trigger effective? I mean, where I can see the rule trigger result?

If I want to import the D2C data to DB2 or other databases engine through the iot platform, it there any way to do that?

**Comment by durera** [comment]
This library does not support rules at present.  At some point in the future we should have that covered in https://github.com/ibm-watson-iot/swagger-java, but it's very early days for that project and it only has coverage of a few basic APIs right now.
