### ISSUE TITLE
Write some decent documentation

### ISSUE THREAD

**Issue by durera** [ibm-watson-iot/iot-java#161]
- Create docs in Markdown in `mkdocs/docs`
- Convert docs to HTML in `docs`
- Publish to GitHub Pages

Create Java equivalent docs for each of these:

- [ ] https://ibm-watson-iot.github.io/iot-python/ (started)
- [ ] https://ibm-watson-iot.github.io/iot-python/application/
- [ ] https://ibm-watson-iot.github.io/iot-python/application/config/
- [ ] https://ibm-watson-iot.github.io/iot-python/application/mqtt/commands/
- [ ] https://ibm-watson-iot.github.io/iot-python/application/mqtt/events/
- [ ] https://ibm-watson-iot.github.io/iot-python/application/mqtt/status/
- [ ] https://ibm-watson-iot.github.io/iot-python/device/
- [ ] https://ibm-watson-iot.github.io/iot-python/device/config/
- [ ] https://ibm-watson-iot.github.io/iot-python/device/managed/
- [ ] https://ibm-watson-iot.github.io/iot-python/gateway/
- [ ] https://ibm-watson-iot.github.io/iot-python/gateway/config/
- [ ] https://ibm-watson-iot.github.io/iot-python/gateway/managed/

**Comment by potatoronin** [comment]
Any progress? would like to see at least in brief "Connection options"

**Comment by akauppi** [comment]
@durera While the front page is all we have, how much use would you say the Python docs you point to would be, to get in grips with the concepts? I'd eventually code in JVM, though.

**Comment by durera** [comment]
Closing issue, IBM Watson IoT Platform has been withdrawn from market as of December 9, 2020. See: https://www-01.ibm.com/common/ssi/cgi-bin/ssialias?subtype=ca&infotype=an&appname=iSource&supplier=897&letternum=ENUS920-136#rprodnx for more information
