### ISSUE TITLE
sample code correction: DeviceClient is not in "app" but "device"? 

### ISSUE THREAD

**Issue by xchenhui** [ibm-watson-iot/iot-java#173]
need modify to "import com.ibm.wiotp.sdk.device.DeviceClient;"
regarding to the sample code in readme as below 

<img width="928" alt="image" src="https://user-images.githubusercontent.com/51153485/58539877-d1b44380-822a-11e9-8ab5-3f8084f33c73.png">

**Comment by durera** [comment]
Thanks for the pointer, will get this fixed  👍
