### ISSUE TITLE
Automatic-Reconnect function is not working in our environment

### ISSUE THREAD

**Issue by sauraba** [ibm-watson-iot/iot-java#174]
When the connection is lost between the MQTT client and server, the client in unable to re-connect.

Automatic-Reconnect property is set to True.

client version is 0.2.7.

**Comment by durera** [comment]
Could you try upgrading to the `com.ibm.wiotp` release ... we've performed a major refactor of the code and published under a new package name.  Auto-reconnect logic was one of a few things that changed.

https://search.maven.org/search?q=com.ibm.wiotp

If you are still having issue, please set the log level to debug and provide a log demonstrating the issues you are having.

**Comment by sauraba** [comment]
Ran the upgraded client using the sample  https://github.com/ibm-watson-iot/iot-java/blob/master/samples/oshi/src/main/java/com/ibm/wiotp/samples/oshi/OshiDevice.java

and got the exception:
Reason Code: 32109 Cause: EOFException

The client ended with following message in the log:  "Closing connection to IBM Watson IoT Platform ..."

How can "Reason Code: 32109 Cause: EOFException" be avoided. Since, we know that no other device connects with the same client ID.

**Comment by JonahLuckett** [comment]
Hiya, I'm having some difficulty re-creating your issue. Any chance you could provide the full log of the problem after setting the log level to debug? Thanks

**Comment by sauraba** [comment]
For testing purposes currently using sample com.ibm.wiotp.samples.oshi jar v 1.0.0 with dependency . Is there a version that has debug enabled I could deploy to a customer's env for further exceptions that may occur?

**Comment by durera** [comment]
We need to understand the context of the exception that you are hitting to determine exactly which scenario/code path you're going down here.  When you run the sample it should generate a log to system out, can you please provide this output .  

You do not need to enable a debug mode or anything like that, just the log messages as-is will be sufficient, we are working to improve the logging for the next release as well, but what is in the version you are using will be sufficient for our needs at the moment.

**Comment by sauraba** [comment]
Sharing the logs from the console with exceptions
[samplelogs.txt](https://github.com/ibm-watson-iot/iot-java/files/3501049/samplelogs.txt)

**Comment by durera** [comment]
@sauraba Please pick up release 0.2.3, this resolves an issue with handling connection timeouts that may have been playing a role in this -- see #176

**Comment by durera** [comment]
In attempting to reproduce, I simply turned my wifi off for 5 minutes or so ... can see in the logs printed to std out that the client disconnected and reconnected automatically .. note there is a delay between network connectivity being restored and Paho client reconnecting (WIoTP code is not involved at all here in the reconnect scenario, we are letting Paho get on with it), the only level we get involved is to log loss/restore of connection in our code.
 
 ```
2019-09-04 10:35:34 INFO  OshiDevice           IBM Watson IoT Platform OSHI Device Client
2019-09-04 10:35:34 INFO  OshiDevice           https://github.com/ibm-watson-iot/iot-java/tree/master/samples/oshi
2019-09-04 10:35:34 INFO  OshiDevice
2019-09-04 10:35:34 INFO  OshiDevice           Welcome to IBM Watson IoT Platform Quickstart, view a vizualization of live data from this device at the URL below:
2019-09-04 10:35:34 INFO  OshiDevice           https://quickstart.internetofthings.ibmcloud.com/#/device/XXX/sensor/
2019-09-04 10:35:34 INFO  OshiDevice
2019-09-04 10:35:34 INFO  OshiDevice           (Press <Ctrl+C> to quit)
2019-09-04 10:35:34 INFO  AbstractClient       Successfully connected to IBM Watson IoT Platform
<<<10:36:12 wifi turned off>>>
2019-09-04 10:36:35 WARN  DeviceClient         Connection lost: Reason Code: 32109 Cause: SocketException: Software caused connection abort: recv failed
<<<10:42:55 wifi turned on>>>
2019-09-04 10:45:06 INFO  DeviceClient         Reconnected to tcp://quickstart.messaging.internetofthings.ibmcloud.com:1883
``` 

Run the sample ( https://search.maven.org/search?q=a:com.ibm.wiotp.samples.oshi ) as we have, and if you see different behaviour please send the logs you get:  `java -jar com.ibm.wiotp.samples.oshi-1.0.1-jar-with-dependencies.jar --quickstart`

**Comment by sauraba** [comment]
exception from connectionLost java.lang.NoClassDefFoundError: org/apache/commons/lang3/exception/ExceptionUtils

was raised when paho client tries to re-connect.  Need to have jar included (dependency) as part of sdk.
