### ISSUE TITLE
GatewayClient Connection lost: MqttException - Unexpected error (6)

### ISSUE THREAD

**Issue by vmariusv** [ibm-watson-iot/iot-java#179]
Hi,

I'm using com.ibm.wiotp.sdk 0.3.0 to create a GatewayClient that sends events/receives commands on behalf of some device. If I register devices through REST API or let the gateway use "Device auto-registration" feature ("_Gateway devices can automatically register devices that are connected to them. When a gateway publishes a message or subscribes to a topic on behalf of an unregistered device, that device is automatically registered._") my GatewayClient is disconnecting / reconnecting on each new device. If the device is already registered, all works without disconnecting / reconnecting.

In the logs I see the following exception which is caused by an unexpected PINGRESP package received that has no corresponding token:
Connection lost: MqttException - Unexpected error (6)
	at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:161)
	at java.lang.Thread.run(Thread.java:748)

Inside CommsReceiver I see the following comments:
// It its an ack and there is no token then something is not right.
// An ack should always have a token assoicated with it.
throw new MqttException(MqttException.REASON_CODE_UNEXPECTED_ERROR);

If I enable more debug logs, I see that keep alive pings are working as expected, so all is ok until a new device is added.

I tried paho version 1.2.1 and 1.2.2, still same result.

**Comment by durera** [comment]
Unfortunately we will not be able to address this bug, IBM Watson IoT Platform has been withdrawn from market as of December 9, 2020. See: https://www-01.ibm.com/common/ssi/cgi-bin/ssialias?subtype=ca&infotype=an&appname=iSource&supplier=897&letternum=ENUS920-136#rprodnx for more information
