### ISSUE TITLE
Quality Of Service - ignored on publish command

### ISSUE THREAD

**Issue by shalver** [ibm-watson-iot/iot-java#18]
I was doing some testing of sending a command via the ApplicationClient to a device that was not currently connected.  I used a "quality of service" value of 3.  I was expecting that the device would receive the message once it connects;  but did not.   I noticed that the "qos" parameter on the publishCommand method is never used; and a value of 0 seems to be send to the mqtt api.

```
    MqttMessage msg = new MqttMessage(payload.toString().getBytes(Charset.forName("UTF-8")));
    msg.setQos(0);
    msg.setRetained(false);
```

**Comment by sathipal** [comment]
Thank you again for reporting the issue. Its fixed now.
