### ISSUE TITLE
Add ability to set memory persistence and buffer size in underlying MQTTAsyncClient

### ISSUE THREAD

**Issue by harrisondkurtz** [ibm-watson-iot/iot-java#184]
Currently the library sets the persistence to Memory and the default buffer size to 5000. Power losses happen with embedded devices so persisting to memory might as well not be persisting at all. The library should at least allow persistence to be turned off so clients can handle buffering messages on their own.

**Comment by durera** [comment]
Closing issue, IBM Watson IoT Platform has been withdrawn from market as of December 9, 2020. See: https://www-01.ibm.com/common/ssi/cgi-bin/ssialias?subtype=ca&infotype=an&appname=iSource&supplier=897&letternum=ENUS920-136#rprodnx for more information
