### ISSUE TITLE
This project is dead - but you can use the MQTT stream directly

### ISSUE THREAD

**Issue by akauppi** [ibm-watson-iot/iot-java#188]
To authors: I don't know why IBM intends to maintain this code base (but doesn't do a very good job with it). After trying to use it, for weeks, I see no added value in it over raw subscription of an MQTT stream.

A better approach for me was to use a generic MQTT client, and listen to the streams via it. Chose the [Alpakka MQTT](https://doc.akka.io/docs/alpakka/current/mqtt.html) connector.

One problem (with both) is that one should explicitly upgrade the Paho client to 1.2.4. That had a fix that was crucial in the project I work with.

**Comment by rdasgupt** [comment]
@akauppi 
FYI: We will have a new iot-java library release by May 8, 2020. This release will use Paho Java MQTTv3 1.2.4.

**Comment by durera** [comment]
> but doesn't do a very good job with it

Dead is an exaggeration, but I'd 100% agree with you here -- it's definitely not as healthy as it should be :) 

> I see no added value in it over raw subscription of an MQTT stream.

Alpakka, Paho, HiveMQ (and many more) libraries are all available to work directly with WIOTP via the MQTT.  This goal of this project is to try to abstract that MQTT layer away, allowing developer to focus on working with events & commands.  It is very much in a pre-release / work in progress state at present, and definitely progressing slower than I'd hoped it would.

Comments in this other issue also appropriate here: https://github.com/ibm-watson-iot/iot-java/issues/187#issuecomment-625741810

> One problem (with both) is that one should explicitly upgrade the Paho client to 1.2.4. That had a fix that was crucial in the project I work with.

com.ibm.wiotp.sdk 0.4.1 is now available, which includes Paho 1.2.4 ... it might take a few hours to show up in Maven central, but is available here already : https://repo1.maven.org/maven2/com/ibm/wiotp/com.ibm.wiotp.sdk/0.4.1/
