### ISSUE TITLE
Use latest version of Paho MQTTv3 Java client library (release 1.2.4)

### ISSUE THREAD

**Issue by rdasgupt** [ibm-watson-iot/iot-java#189]
Update project to use 1.2.4 of paho.mqtt.java
https://github.com/eclipse/paho.mqtt.java/releases/tag/v1.2.4

**Comment by durera** [comment]
Done.  https://repo1.maven.org/maven2/com/ibm/wiotp/com.ibm.wiotp.sdk/0.4.1/ includes paho 1.2.4
