### ISSUE TITLE
reconnect can not be interrupted

### ISSUE THREAD

**Issue by shalver** [ibm-watson-iot/iot-java#19]
The clients will auto reconnect when they detect that the connection has been lost.  I think this is a good feature;  but I noticed that if an application wants to close down the client but remain running, this reconnect thread will keep trying forever.  Should there be some association with a call to disconnect() that would break out of this loop?

**Comment by sathipal** [comment]
Hi, can you please post a code that keeps retrying? I'm not able to recreate the issue.

**Comment by shalver** [comment]
Consider the following scenario:

1)  Client is connected
2)  Watson Iot Platform connection is lost and detected
3)  reconnect() is issues to wait for a new connection
4)  Client wishes to disconnect()  and clean up the connection because it its no longer necessary
5)  Client reconnect thread remains active and eventually establishes a new connection but the object has been abandoned.

My thought was that a call to disconnect() could set a flag indicating that the connection has been closed.  The loop that does the retrying could look at this flag and abort if a disconnect has been performed.   I can code up a proposed solution and post it when I get a chance.

Thank you for considering.

**Comment by sathipal** [comment]
Fixed the issue and released a new version of the library - https://github.com/ibm-messaging/iot-java/releases/tag/0.0.12.
