### ISSUE TITLE
cleanSession option wrong setup

### ISSUE THREAD

**Issue by fastchatter** [ibm-watson-iot/iot-java#193]
hello
working with lib version com.ibm.wiotp:com.ibm.wiotp.sdk:0.4.1

`cleanSession` (mqttv3) option was replaced with `cleanStart` and `sessionExpiry` (mqttv5), though mqttv5 is not used actually
we can see that `cleanStart` is used the same way as `cleanSession`:
https://github.com/ibm-watson-iot/iot-java/blob/00b30389a8285a4ccf8ea65f2480b4e28afde37a/src/main/java/com/ibm/wiotp/sdk/app/config/ApplicationConfig.java#L77
https://github.com/ibm-watson-iot/iot-java/blob/00b30389a8285a4ccf8ea65f2480b4e28afde37a/src/main/java/com/ibm/wiotp/sdk/app/config/ApplicationConfigOptionsMqtt.java#L18

for some reason `cleanSession` considered as an opposite of `cleanStart`:
https://github.com/ibm-watson-iot/iot-java/blob/00b30389a8285a4ccf8ea65f2480b4e28afde37a/src/main/java/com/ibm/wiotp/sdk/app/config/ApplicationConfig.java#L121-L124

`cleanSession` option is used only in one place - decision if client needs to resubscibe:
https://github.com/ibm-watson-iot/iot-java/blob/00b30389a8285a4ccf8ea65f2480b4e28afde37a/src/main/java/com/ibm/wiotp/sdk/app/ApplicationClient.java#L391-L411

**Issue**: with `cleanStart=true` (which means `connectOptions.setCleanSession(true)` in case of temporary disconnect subscriber no longer receives messages after reconnect.
inversion of `cleanSession` in case of `cleanStart=true` leads to omitting re-subscription.

Inversion of `cleanStart`:
https://github.com/ibm-watson-iot/iot-python/blob/f49ae9a1008f7059d50992002c1e7b9c5ed71d0b/src/wiotp/sdk/client.py#L131-L132

I guess this could be related to similar logic in python version of client, commit https://github.com/ibm-watson-iot/iot-python/commit/1bda33301591c7e122003b0728ae8a3cf2ef4297 description says
> options.mqtt.cleanStart (opposite of cleanSession, converted for now while we still have a MQTTv3 library in place)
Original reasoning can be related to opposite default values: `cleanSession=true` and `cleanStart=false`.

I don't know exactly what is original reasoning behind "cleanSession is inversion of cleanStart", but the logic is wrong, `cleanStart` and `cleanSession` should have equal values despite of their defaults.
> When clean start is set to true and session expiry is 0, the buffer is reset.
> When clean session is set to true, the buffer is reset.

[ibm iot docs](https://www.ibm.com/support/knowledgecenter/cs/SSQR84_monitor/iot/platform/reference/mqtt/restrictions_limitations.html)

**How to fix without lib tweaking**: 
```java
class ApplicationConfigWithCleanSession extends ApplicationConfig {

    public ApplicationConfigWithCleanSession(ApplicationConfigIdentity identity, ApplicationConfigAuth auth, ApplicationConfigOptions options) {
        super(identity, auth, options);
    }

    @Override
    public boolean isCleanSession() {
        return options.mqtt.cleanStart;
    }
}
```
With tweaked config subscriber receives messages after reconnect.

**Comment by durera** [comment]
Unfortunately we will not be able to address this issue, IBM Watson IoT Platform has been withdrawn from market as of December 9, 2020. See: https://www-01.ibm.com/common/ssi/cgi-bin/ssialias?subtype=ca&infotype=an&appname=iSource&supplier=897&letternum=ENUS920-136#rprodnx for more information
