### ISSUE TITLE
not able to add device  from the java api

### ISSUE THREAD

**Issue by MuralikrishnaM** [ibm-watson-iot/iot-java#22]
Hi Team
From the past 1 hour iam facing one issue, iam not able to add device using the java api, Iam facing the bellow mention problem, the same code piece is working fine earlier.

"Exception in thread "main" com.ibm.iotf.client.IoTFCReSTException: The authentication token is empty or invalid"

Can you please help me on this

**Comment by MuralikrishnaM** [comment]
Hello team can you please respond, does it has any problem?

**Comment by sathipal** [comment]
@MuralikrishnaM, Were you able to add the device manually? have you tried? Also, can you give us more hint on the API that you are using to add the device? Also the parameters.

The exception is thrown when the Authentication token is invalid. I can verify with the team based on the details that you give.

**Comment by MuralikrishnaM** [comment]
I could be able to add the device manually, I spent lot of time on the other day, but it started working from this morning on its own. 
I am running this java class "SampleBulkAPIOperations.java", which throwed error last night, and was working fine from today morning. 
The properties that iam using are:
id = iotf-service
Organization-ID = s5arrk
Authentication-Method = apikey
API-Key = a-s5arrk-iowpabseo3
Authentication-Token = ysvL-FuzNGaM8vGcPP

I wanted to know how frequently we can expect this behavior?

**Comment by miketran78727** [comment]
@MuralikrishnaM Is this still a problem?  If not, could we close this issue?

**Comment by miketran78727** [comment]
@sathipal I think we can close this issue now. I have not seen this issue in any of our testings.

**Comment by sathipal** [comment]
yup, let us close this issue.

@MuralikrishnaM, Please reopen if you see the issue again.
