### ISSUE TITLE
Not able to register new device

### ISSUE THREAD

**Issue by NitishDeshpande** [ibm-watson-iot/iot-java#37]
I am trying to register a device to IoT Platform using the java client library. Here is my code,

```
            try {
                client.connect();               
                JsonObject deviceInfo = new JsonObject();
                deviceInfo.addProperty("manufacturer", "Philips");
                deviceInfo.addProperty("model", "m001");

                JsonObject location = new JsonObject();
                deviceInfo.addProperty("longitude", 8.107910);
                deviceInfo.addProperty("latitude", 8.525342);
                deviceInfo.addProperty("elevation", 0);
                deviceInfo.addProperty("accuracy", 0);
                deviceInfo.addProperty("measuredDateTime", "2016-07-15T12:21:50.879Z");

                JsonObject metadata = new JsonObject();
                deviceInfo.addProperty("manufacturer", "Philips");
                deviceInfo.addProperty("model", "m001");

                client.api().registerDevice("LightBulb", "LB002", "&wR+6LHX_QcxwXz4Po", deviceInfo, location, metadata);

            } catch (MqttException | IoTFCReSTException e) {
                e.printStackTrace();
                return;
            } finally {
                System.out.println("Closing connection to the IBM Watson IoT Platform");
                // Once told to stop, cleanly disconnect from the service
                client.disconnect();
            }
```

On running this code I am getting a **IoTFCReSTException** saying,

```
2016-07-15 19:30:16.221  INFO 10236 --- [nio-8080-exec-1] com.ibm.iotf.util.LoggerUtility          : http-nio-8080-exec-1: Successfully connected to the IBM Watson IoT Platform

com.ibm.iotf.client.IoTFCReSTException: Invalid request (No body, invalid JSON, unexpected key, bad value)
    at com.ibm.iotf.client.api.APIClient.registerDevice(APIClient.java:1723)
    at com.ibm.iotf.client.api.APIClient.registerDevice(APIClient.java:1666)
    at com.mindtree.coe.iot.watson.services.AssetsService.addInternetCapableAsset(AssetsService.java:66)
    at com.mindtree.coe.iot.watson.controllers.AssetsController.addNewAsset(AssetsController.java:26)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
// ... more exception stack trace

2016-07-15 19:30:17.980  INFO 10236 --- [nio-8080-exec-1] com.ibm.iotf.util.LoggerUtility          : http-nio-8080-exec-1: Successfully disconnected from from the IBM Watson IoT Platform
```

What could possibly the issue?

P.S. - There is a device type called **LightBulb** created in the platform. Manual creation of the device in the IoT platform through the browser works perfectly

**Comment by whitfiea** [comment]
The JsonObjects for location and metadata are empty, this is why the exception is being thrown.

You are adding all the properties to the same JsonObject called "deviceInfo" when you should be adding the location properties to "location" and metadata to "metadata" etc.

**Comment by NitishDeshpande** [comment]
@whitfiea Corrected the typo (my bad).. Still getting the same error

**Comment by whitfiea** [comment]
@NitishDeshpande can you add `System.out.println(e.getResponse())` when you catch the exception as this will output the json response returned from the platform.

**Comment by NitishDeshpande** [comment]
The response is,
`{"violations":[{"message":"CUDRS0053E: The authToken field was not a valid password. The password must be between 8 and 36 characters long (inclusive). The password must consist only of alpha-numerical characters plus hyphen ( - ), underscore ( _ ) or period ( . ).","exception":{"id":"CUDRS0053E","properties":["authToken"]}}],"message":"CUDRS0007E: The request was not valid. Review the constraint violations provided.","exception":{"id":"CUDRS0007E","properties":[]}}`

This Auth token is the one which is generated when we create an API key for our application.

Is registering the device same as adding a device to IoT platform?

**Comment by whitfiea** [comment]
@NitishDeshpande the authToken you pass in on this call is one to be associated with the device you are registering rather than the one generated from the API key. It is up to you what the authToken would be (and you can leave it out of the call to have one generated for you https://github.com/ibm-watson-iot/iot-java/blob/8909760bd9ed40494db763b1611a0ffb606020c1/src/main/java/com/ibm/iotf/client/api/APIClient.java#L1634 ).

The restrictions on the authToken field are defined in that error message. Use an entry that will pass the restrictions, and not the authtoken from the api-key.

**Comment by NitishDeshpande** [comment]
@whitfiea thanks. It worked :)
