### ISSUE TITLE
Local build with test failures

### ISSUE THREAD

**Issue by miketran78727** [ibm-watson-iot/iot-java#39]
What are the prerequisites before running the tests?  I know that I need to generate API-key and token.  Do I need to create device type or device(s) in the UI prior to building the iot-java library?  Please provide sample required updates to the properties files in test/resources directory.

**Comment by sathipal** [comment]
In order to run the tests, we need to have the device & gateway registered in the Platform. there are 3 properties file in the test/resources directory - all of them needs to be filled.

**Comment by miketran78727** [comment]
@sathipal It's better now, but there are still a number of failures:

Failed tests: 
  DeviceCommandSubscriptionTest.testCommandReception:87 Device Event is not received by application
  ApplicationEventSubscriptionTest.test01EventSubscribe:132 Device Event is not received by application
  ApplicationEventSubscriptionTest.test02Subscribe:628 Device Event is not received by application
  ApplicationEventSubscriptionTest.test07Subscribe:780 Device Event is not received by application
  GatewayCommandSubscriptionTest.testDeviceCommandUnsubscription:278 The command should not be received by gateway
  GatewayCommandSubscriptionTest.test04DeviceCommandUnsubscription:353 The command should not be received by gateway
  GatewayCommandSubscriptionTest.test03DeviceCommandUnsubscription:328 The command should not be received by gateway
  GatewayCommandSubscriptionTest.test02DeviceCommandUnsubscription:303 The command should not be received by gateway

Tests in error: 
  DeviceManagementTest.test06FirmwareDownload:338 » IoTFCReST Failure in initiat...
  DeviceManagementTest.test07FirmwareUpdate:369 » IoTFCReST Failure in initiatin...
  DeviceManagementTest.test08RebootRequest:263 » IoTFCReST Failure in initiating...

Tests run: 121, Failures: 8, Errors: 3, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15:32 min
[INFO] Finished at: 2016-07-19T21:39:47+01:00
[INFO] Final Memory: 23M/59M

**Comment by sathipal** [comment]
I modified the Gateway related tests and they are passing now. But regarding other test failures, the application.properties must be set with the same device-id that is set in the device.properties file.

The latest build/test status is here - http://9.124.102.159:8080/job/Watson-IoT-Java/lastBuild/
