### ISSUE TITLE
AppClient adds additional attributes to payload on CommandPublish

### ISSUE THREAD

**Issue by potatoronin** [ibm-watson-iot/iot-java#50]
Example:
Intended payload
{"myNumber":201601,"Message":"Test","Interval":30}

Payload received by device:
{**"d":**{"myNumber":201601,"Message":"Test","Interval":30},"**ts**":"2016-08-18T10:15:40.108+0000"}

This is very inconvenient due to following reasons:
1) Requirement for having Parent D attribute has been deprecated by IoTF a long time ago
2) NodeJS library we use for other application but for communication with the same device Passes the payload AS-IS with No modification

Please, consider changing the CommandPublish function so that it would Not Modify InputData.

**Comment by sathipal** [comment]
The pull request https://github.com/ibm-watson-iot/iot-java/pull/58 contains fix for this issue.

**Comment by sathipal** [comment]
Closing as the pull request #58 contains the fix for this issue.
