### ISSUE TITLE
API support for creating message source, message schema, rules, actions and alerts

### ISSUE THREAD

**Issue by NitishDeshpande** [ibm-watson-iot/iot-java#51]
Is there a API support for creating message source, message schema, rules, actions and alerts? I see that the capabilities of Real time Insights are added into the Watson IoT platform. Are these capabilities going to be added in the next versions of the client library? If not, are there REST APIs to achieve the same thing?

**Comment by sathipal** [comment]
There is no API exposed as of now. We ll include it in the library whenever the REST APIs are exposed by the platform.

**Comment by NitishDeshpande** [comment]
Any idea on when the APIs will be exposed on the platform?

**Comment by sathipal** [comment]
No, we don't have the date yet. Once there is a support, we will add the same into the library.

**Comment by sathipal** [comment]
Closing the issue as we will address this issue later when there is a support from the Platform.
