### ISSUE TITLE
whether in the future the same library for LUA?

### ISSUE THREAD

**Issue by EduardShaid** [ibm-watson-iot/iot-java#56]
whether in the future the same library for LUA?

**Comment by sathipal** [comment]
Thank you for your interest in LUA library. Could you please add more details about your requirement? Right now there is no plan to create a library for LUA. But, if more people are requiring it then we can add a support.

**Comment by sathipal** [comment]
Closing the issue as its not related to this library. And if there are more interests, we ll try to create a library for LUA.
