### ISSUE TITLE
DeviceClient.publishEventOverHTTP() with quickstart gets 307?

### ISSUE THREAD

**Issue by dlaboss** [ibm-watson-iot/iot-java#79]
I'm trying to use the above API in iot-java 0.1.5 with quickstart.  The operation fails.  Apparently it isn't forming the correct URL w/port?

```
SEVERE: pool-1-thread-7-IotpQuickstart: HTTP Code: 307
URL: http://quickstart.internetofthings.ibmcloud.com/api/v0002/device/types/iotsamples-edgent/devices/qs29f8fc114c1443d4/events/sensors
...
Location http://quickstart.messaging.internetofthings.ibmcloud.com:1883/api/v0002/device/types/iotsamples-edgent/devices/qs29f8fc114c1443d4/events/sensors
```

Is there anything I can do to make it work w/0.1.5?

Same thing happens w/0.2.2 with that, now deprecated, method... though  ```deviceClient.api().publishDeviceEventOverHTTP()``` does work.  Is 0.2.2 with the APIClient method the only viable option?

**Comment by sathipal** [comment]
HTTP Status Code 307: The target resource resides temporarily under a different URI.

`DeviceClient.publishEventOverHTTP()` method is deprecated as the REST URI is changed at Watson IoT Platform recently. Please use `deviceClient.api().publishDeviceEventOverHTTP()` to make any API call going forward.
