### ISSUE TITLE
device.Command.getData() returns byte[] for json cmd format

### ISSUE THREAD

**Issue by dlaboss** [ibm-watson-iot/iot-java#81]
I'm encountering this with 0.2.2 and the master branch seems to be unchanged relative to this.  Based on getData()'s doc I would have expected JsonObject or String.
Message's ctor does [this.payload = msg.getPayload()](https://github.com/ibm-watson-iot/iot-java/blob/master/src/main/java/com/ibm/iotf/client/Message.java#L92).  
I'm guessing the intent was that the json processing flow below that should have a `this.payload = payloadJson` but it doesn't.

**Comment by sathipal** [comment]
@dlaboss  Yes, the code changes are missing. We ll address it.

**Comment by sathipal** [comment]
@dlaboss the fix is released into new version 0.2.3. Please review and close.

**Comment by dlaboss** [comment]
Thanks!
