### ISSUE TITLE
GatewayClient.getDeviceId() returns null when Gateway-ID key is used

### ISSUE THREAD

**Issue by dlaboss** [ibm-watson-iot/iot-java#82]
With 0.2.2, when the config properties use the new style `Gateway-ID` key instead of the old `id`
`GatewayClient.getDeviceId()` returns `null`.  `getGWDeviceId()` is correct.

`GatewayClient` needs to override `AbstractClient.getDeviceId()`.

**Comment by sathipal** [comment]
@dlaboss the fix is released into new version 0.2.3. Please review and close.

**Comment by dlaboss** [comment]
Thanks!
