### ISSUE TITLE
GatewayClient.api().publishDeviceEventOverHTTP fails

### ISSUE THREAD

**Issue by dlaboss** [ibm-watson-iot/iot-java#85]
w/v0.2.2  I have successfully used `DeviceClient.api().publishDeviceEventOverHTTP()`.

I wanted to do likewise from a GatewayClient, for events from the GW device id as well as events from its connected devices.

`GatewayClient.api().publishDeviceEventOverHTTP()` throws
```
Exception in thread "main" com.ibm.iotf.client.IoTFCReSTException: The authentication method is invalid or the API key used does not exist
	at com.ibm.iotf.client.api.APIClient.publishMessageOverHTTP(APIClient.java:3307)
	at com.ibm.iotf.client.api.APIClient.publishDeviceEventOverHTTP(APIClient.java:3338)
	at org.apache.edgent.samples.connectors.iotp.IotpGWClient.publishEventOverHTTP(IotpGWClient.java:78)

```

My GW registration/cfg-file info is correct as the same cfg info works fine for MQTT publish events and receive cmds.

Also, how does my gateway publish connected device's events over HTTP via GatewayClient.api()?

**Comment by miketran78727** [comment]
Currently, Watson IoT Platform does not support publishing events for connected device from a gateway **via HTTP**.  The "**HTTP POST for gateways**" function will be available as a beta feature in a few weeks.  I will update the client library to add this new feature as well.

**Comment by dlaboss** [comment]
Thanks Mike.  Re, your first sentence, I assume that only applies to publishing via HTTP.  Did I miss doc indicating the state of various parts of the GatewayClient / APIClient API?  Are there other things I should be aware of?  I'm enhancing Apache Edgent to include a connector to WIoTP to enable Edgent applications to operate as a gateway device.

**Comment by miketran78727** [comment]
Oops, you're right.  I meant to say "via HTTP".  I corrected my previous comment.

**Comment by miketran78727** [comment]
If your application is using HTTP protocol, check our current documentation: https://console.ng.bluemix.net/docs/services/IoT/applications/api.html
If your device is using HTTP protocol, see https://console.ng.bluemix.net/docs/services/IoT/devices/api.html
We will have a new page to document HTTP support for gateways.

**Comment by amprasanna** [comment]
@dlaboss - The Documentation pages have been updated to include the support for HTTP Messaging API's for Gateways & Devices. Please find them as mentioned below:
[Gateways](https://console.ng.bluemix.net/docs/services/IoT/gateways/gw_intro_api.html#api):
https://console.ng.bluemix.net/docs/services/IoT/gateways/gw_intro_api.html#api
[Devices](https://console.ng.bluemix.net/docs/services/IoT/devices/device_cmd_api.html#api):
https://console.ng.bluemix.net/docs/services/IoT/devices/device_cmd_api.html#api
