### ISSUE TITLE
Proxy support for DeviceFactory

### ISSUE THREAD

**Issue by royjfrancois** [ibm-watson-iot/iot-java#9]
Seems like the Java proxy configuration is ignored by the DeviceFactory.connect() method, which causes DeviceFactory.getDevices() (as well as other public methods) to fail:

WARNING: Connect to internetofthings.ibmcloud.com:443 [internetofthings.ibmcloud.com/158.85.136.146] failed: Connection refused: connect

Setting a RequestConfig to the request built by DeviceFactory.connect() does the trick.

Ex:

HttpGet get = new HttpGet(url);

//begin fix
HttpHost proxy = new HttpHost("myproxy.com", 3128);
RequestConfig config = RequestConfig.custom().setProxy(proxy).build();
get.setConfig(config);
//end fix

Is there any plan to introduce support of proxies?
Maybe using System properties https.proxyHost and https.proxyPort?

Thanks!

**Comment by sathipal** [comment]
Closing as this is a very old issue.

The recent changes in the library allows once to get proxy support. Run the application with the following JVM parameters to get the proxy support.
-Dhttps.proxyPort=80 -Dhttps.proxyHost=proxyserver.mycompany.com
