### ISSUE TITLE
Getting java.net.UnknownHostException on 0.2.4 version

### ISSUE THREAD

**Issue by rejaultcs** [ibm-watson-iot/iot-java#93]
Getting following unknown host error (log below) while using 0.2.4 version.

I am accessing my platform using this link https://7pk5lv.internetofthings.ibmcloud.com/#/ which doesn't have "messaging" after org id and it opens correctly.

Is there any quick way to test if this URL is correct or not?
ssl://7pk5lv.messaging.internetofthings.ibmcloud.com:8883

Apr 07, 2017 6:32:17 PM com.ibm.iotf.client.AbstractClient createClient
INFO: main: Org ID    = 7pk5lv
         Client ID    = d:7pk5lv:VehicleTele:KarimVehicleTele
CONNECTING
Apr 07, 2017 6:32:17 PM com.ibm.iotf.client.AbstractClient connect
INFO: main: Connecting client d:7pk5lv:VehicleTele:KarimVehicleTele to ssl://7pk5lv.messaging.internetofthings.ibmcloud.com:8883 (attempt #1)...
Published the event successfully !
Apr 07, 2017 6:32:28 PM com.ibm.iotf.client.AbstractClient connect
SEVERE: main: Connecting to Watson IoT Platform failed
MqttException (0) - java.net.UnknownHostException: 7pk5lv.messaging.internetofthings.ibmcloud.com
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:690)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.UnknownHostException: 7pk5lv.messaging.internetofthings.ibmcloud.com
	at java.net.InetAddress.getAllByName0(Unknown Source)
	at java.net.InetAddress.getAllByName(Unknown Source)
	at java.net.InetAddress.getAllByName(Unknown Source)
	at java.net.InetAddress.getByName(Unknown Source)
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:75)

**Comment by rahuldatasc** [comment]
from command prompt ping to the host  7pk5lv.messaging.internetofthings.ibmcloud.com

If you are able to ping then your host is correct otherwise you may be no more a member of this organization '7pk5lv'

**Comment by miketran78727** [comment]
I commented on stackoverflow. 

http://stackoverflow.com/questions/43660084/i-cant-deviceclient-connect-to-a-device-created-with-a-gatewayclient-on-the-i/43668613#43668613

When you connect over MQTT for messaging, the messaging address is: 

````
<org>.messaging.internetofthings.ibmcloud.com
````
You can use secure ports, 8883 or 443, or non-secure port 1883. By default, this Java client library connects using secure port 8883.

You can use openssl to check if the SSL port is listening

````
openssl s_client -connect 7pk5lv.messaging.internetofthings.ibmcloud.com:8883
````

**Comment by amprasanna** [comment]
@rejaultcs - Can you please confirm / acknowledge, if the above mentioned response from Mike Tran resolved your issue?
